In [14]:
import numpy as np
import pandas as pd

#Starting to inspect the dataset

In [16]:
links_df = pd.read_csv('links.csv')
links_df.head(10)

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0
5        6  113277    949.0
6        7  114319  11860.0
7        8  112302  45325.0
8        9  114576   9091.0
9       10  113189    710.0

In [17]:
movies_df = pd.read_csv('movies.csv')
movies_df.head(10)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller

In [18]:
ratings_df = pd.read_csv('ratings.csv')
print("Movies:",movies_df.shape)
print("Ratings:",ratings_df.shape)
ratings_df.head(10)

Movies: (9742, 3)
Ratings: (100836, 4)

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931
5       1       70     3.0  964982400
6       1      101     5.0  964980868
7       1      110     4.0  964982176
8       1      151     5.0  964984041
9       1      157     5.0  964984100

In [19]:
tags_df = pd.read_csv("tags.csv")
tags_df.head(10)

#if one person likes a set of movie and another person likes other set with few movies in common so they can like the movies from each other's set also.

   userId  movieId                tag   timestamp
0       2    60756              funny  1445714994
1       2    60756    Highly quotable  1445714996
2       2    60756       will ferrell  1445714992
3       2    89774       Boxing story  1445715207
4       2    89774                MMA  1445715200
5       2    89774          Tom Hardy  1445715205
6       2   106782              drugs  1445715054
7       2   106782  Leonardo DiCaprio  1445715051
8       2   106782    Martin Scorsese  1445715056
9       7    48516       way too long  1169687325

In [20]:
# so merge the ratings and movie dataset

df = movies_df.merge(ratings_df, on='movieId')
df

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,964982703
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5,4.0,847434962
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,4.5,1106635946
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.5,1510577970
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17,4.5,1305696483
...,...,...,...,...,...,...
100831,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,184,4.0,1537109082
100832,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,184,3.5,1537109545
100833,193585,Flint (2017),Drama,184,3.5,1537109805
100834,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,184,3.5,1537110021
100835,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,331,4.0,1537157606

In [21]:
# creating a title and stored it in list of recommended movies.
T_s = '101 Dalmatians (1996)'
recommended_movies = []

#find movie in dataset and sort it as per ratings
movie_db = df[df['title'] == T_s]\
            .sort_values(by='rating', ascending=False)

#get first 5 users who liked this movie
for user in movie_db.iloc[:5]['userId'].values:
    
    #get rated movies from this user
    rated_movies = df[df['userId'] == user]
    
    #get the five biggest rated movie by this user
    rated_movies = rated_movies[rated_movies['title'] != T_s]\
                        .sort_values(by='rating', ascending=False)\
                        .iloc[:5]
    
    #add these to the recommendations
    recommended_movies.extend(list(rated_movies['title'].values))
    
 
recommended_movies = np.unique(recommended_movies)
    
for movie in recommended_movies:
    print(movie)

City of Lost Children, The (Cité des enfants perdus, La) (1995)
Clueless (1995)
Dazed and Confused (1993)
Fargo (1996)
Father of the Bride Part II (1995)
Four Weddings and a Funeral (1994)
Godfather, The (1972)
Independence Day (a.k.a. ID4) (1996)
Jerry Maguire (1996)
Leaving Las Vegas (1995)
Little Miss Sunshine (2006)
Love Actually (2003)
Miracle on 34th Street (1994)
Mrs. Doubtfire (1993)
Pirates of the Caribbean: Dead Man's Chest (2006)
Rock, The (1996)
Seven (a.k.a. Se7en) (1995)
Star Wars: Episode IV - A New Hope (1977)
Star Wars: Episode VI - Return of the Jedi (1983)
The Jungle Book (2016)
Toy Story (1995)
Twelve Monkeys (a.k.a. 12 Monkeys) (1995)
Wanted (2008)

In [23]:
#now weigth each movie by the similarity on the genre features

gmovie_genres = df[df['title']==T_s].iloc[0]['genres'].split('|')
scores = {}

for movie in recommended_movies:
    movied = df[df['title']==movie].iloc[0]
    movie_genres = movied['genres'].split('|')
    score = 0
    
    #scoring on how many gmovie_genre can be found in movie_genres?
    for gmovie_genre in gmovie_genres:
        if gmovie_genre in movie_genres:
            score += 1
            
    scores[movie] = score
    
#Sort them on score and reserve it, because the bigger the score the better
recommended_movies = sorted(scores, key=lambda x: scores[x])[::-1]

In [25]:
#the recommendations are now weighted

for movie in recommended_movies:
    print(movie)

Toy Story (1995)
Little Miss Sunshine (2006)
City of Lost Children, The (Cité des enfants perdus, La) (1995)
Clueless (1995)
Dazed and Confused (1993)
Fargo (1996)
Father of the Bride Part II (1995)
Four Weddings and a Funeral (1994)
Independence Day (a.k.a. ID4) (1996)
Love Actually (2003)
Mrs. Doubtfire (1993)
Pirates of the Caribbean: Dead Man's Chest (2006)
Rock, The (1996)
Star Wars: Episode IV - A New Hope (1977)
Star Wars: Episode VI - Return of the Jedi (1983)
The Jungle Book (2016)
Godfather, The (1972)
Jerry Maguire (1996)
Leaving Las Vegas (1995)
Miracle on 34th Street (1994)
Seven (a.k.a. Se7en) (1995)
Twelve Monkeys (a.k.a. 12 Monkeys) (1995)
Wanted (2008)